server.port=8088
spring.application.name=infraestructure-keycloak
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:host.docker.internal}:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.healthcheck.enabled=true
management.endpoints.web.exposure.include=*
spring.cloud.compatibility-verifier.enabled=false


#Para no usar el servidor de configuracion con el micorservicio de configSever
spring.cloud.config.enabled=false

keycloak.base-uri=${KEYCLOAK_SERVER:http://host.docker.internal:8091/realms/ecommerce/protocol/openid-connect/}
keycloak.authorization-uri=${keycloak.base-uri}auth
keycloak.user-info-uri=${keycloak.base-uri}userinfo
keycloak.token-uri=${keycloak.base-uri}token
keycloak.logout=${keycloak.base-uri}logout
keycloak.jwk-set-uri=${keycloak.base-uri}certs
keycloak.certs-id=${KEYCLOAK_REAL_ID:QzljS1onq8qHGOiblVOti566lUA9vdYTQ-MEufWA_MU}

#create user Autentificacion Administrador solo del reino master
keycloak.admin-username=admin
keycloak.admin-password=123456


# Configuración del servicio de correo
email.service.uri=http://192.168.246.110:8088/email


# Url del frontend de ResetPassword
frontend.resetPasswordUrl=http://localhost:8083/RestablecerContrasenia


keycloak.client-secret=nU9R8lRpYeG41gQ3JQCR5Z3KKcsvmnBL
keycloak.client-id=frontend-ecommerce
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token

logging.level.root=INFO


#Keycloak.admin.client-id=admin