spring.application.name=api-gateway
# Puerto del Gateway
server.port=8080
spring.cloud.compatibility-verifier.enabled=false


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ==================================================
#                 CUSTOMER-SERVICE
# ==================================================
spring.cloud.gateway.routes[0].id=customer-service
spring.cloud.gateway.routes[0].uri=lb://customer-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/customer/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/customer/(?<segment>.*), /api/v1/customers/$\{segment}

# ==================================================
#                 PRODUCT-SERVICE
# ==================================================
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/product/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/product/(?<segment>.*), /api/v1/products/$\{segment}

# ==================================================
#                 ORDER-SERVICE
# ==================================================
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://order-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/order/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/order/(?<segment>.*), /api/v1/orders/$\{segment}


logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.web=INFO
